//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AquariumGUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AquariumGUI.labels", typeof(labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AERATOR.
        /// </summary>
        internal static string aerator {
            get {
                return ResourceManager.GetString("aerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed only integer..
        /// </summary>
        internal static string AllowedIntegers {
            get {
                return ResourceManager.GetString("AllowedIntegers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed only letters..
        /// </summary>
        internal static string AllowedLetters {
            get {
                return ResourceManager.GetString("AllowedLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type of animal..
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab.
        /// </summary>
        internal static string Crab {
            get {
                return ResourceManager.GetString("Crab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create object..
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string Fish {
            get {
                return ResourceManager.GetString("Fish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set weight in grammes:.
        /// </summary>
        internal static string grammes {
            get {
                return ResourceManager.GetString("grammes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light .
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new name:.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string off {
            get {
                return ResourceManager.GetString("off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open grid form..
        /// </summary>
        internal static string OpenGridForm {
            get {
                return ResourceManager.GetString("OpenGridForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seaweeds.
        /// </summary>
        internal static string Seaweeds {
            get {
                return ResourceManager.GetString("Seaweeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select type.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shellfish.
        /// </summary>
        internal static string Shellfish {
            get {
                return ResourceManager.GetString("Shellfish", resourceCulture);
            }
        }
    }
}
